### ISSUE TITLE
Не работает кнопка "Пользователь" у модератора

### ISSUE THREAD

**Issue by Dmitriy-Bychkov** [Dmitriy-Bychkov/Course_project_6.mailer#4]
@alfa24 
Мои мысли: скорее всего не работает потому, так как джанго контроллер MailingListView обрабатывает вверенный ему на управление шаблон mailing_list.htm и соотвю в нем подтягиваются только обьекты из модели mailing приложения mail, а мы запрашиваем данные у модели совсем другого приложения - users. Нужно как то их подружить, чтобы при нажатии на эту кнопку мы переходили сразу на редактирование пользователя, кому принадлежит текущая рассылка.

Если поменять в ссылке mailing.pk на user.pk то во всех рассылках будет переход на одного и того же пользователя с ИД=2, хотя у рассылок разные пользователи.

Вот сама кнопка:
https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/20808abd9f9498b36924cd3e9d5cf9d29f71eaa1/mail/templates/mail/mailing_list.html#L87-L88

Вот контроллер:
https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/20808abd9f9498b36924cd3e9d5cf9d29f71eaa1/mail/views.py#L164

**Comment by Dmitriy-Bychkov** [comment]
А пользователь с кодом в ссылке user.pk подтягивается тот, кем мы зашли на сайт (это именно и есть модератор, проверил через БД), а должен любой, чья рассылка.

**Comment by alfa24** [comment]
@Dmitriy-Bychkov владелец рассылки хранится в поле owner, соответственно мы должны использовать его id

попробуй так
` <a href="{% url 'users:edit_user' mailing.owner_id %}" `

**Comment by Dmitriy-Bychkov** [comment]
@alfa24
Это сработало, ура!
Работает и так "mailing.owner_id" и так "mailing.owner.pk"
Блогодарю:)
