### ISSUE TITLE
Кеширование страниц

### ISSUE THREAD

**Issue by Dmitriy-Bychkov** [Dmitriy-Bychkov/Course_project_6.mailer#6]
@alfa24
Есть вопрос о правильности применения кеширования. 
Нужно для курсовой добавить 2 вида кеширования: низкоуровневое и на контроллеры напрямую (в урлах).
1) Я решил низкоуровневое добавить на список статей блога:
https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/0779f0f05346f7b5b65c829cf6a71c8b50a29b59/blog/services.py#L6C6-L17C12
+ прописал это в контроллере:
https://github.com/Dmitriy-Bychkov/Course_project_6.mailer/blob/0779f0f05346f7b5b65c829cf6a71c8b50a29b59/blog/views.py#L12C8-L17C15
Непонятно работает или нет, по тому что время загрузки не изменилось при обновлении страницы, хотя иногда блок стал подтупливать-а именно иногда вместо списка статей пусто, обновление страницы помогает.

2) Кеширование всего котроллера:
если я прописываю например вот здесь таким образом - cache_page(60)

path('mailings/mailing_list/', cache_page(60)(MailingListView.as_view()), name='mailing_list'),

То работу кеширования видно сразу, время загрузки падает в 5 раз, но есть обратная сторона, если например выйти из сайта пользователем, или обновить статус рассылки или удалить рассылку, то показывается все еще старая информация на странице. Обновление не всегда помогает (раз через 5 или дольше) 
Как это побороть? или это особенность кеширования всего контроллера?

**Comment by alfa24** [comment]
@Dmitriy-Bychkov 
1. тут ты кешируешь queryset, поэтому лучше наверное будет подключить это в методе get_queryset
2. да, тут так и будет работать, потому что в данном случае ключ кеша будет для всех пользователей одинаковый. А тебе нужен кеш для каждого пользователя свой. Ведь список рассылок у них различается. Для этого надо кешировать не всю view (на данном этапе мы еще не определили пользователя), а в методе GET. Там в параметрах уже присутствует pk пользователя. А ключ кеша строится по названию функции и ее аргументам (но это не точно).
